import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Poppins } from 'next/font/google';
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased px-7 py-10`}
      >
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
